### ISSUE TITLE
enh: output reference base in the pileup

### ISSUE THREAD

**Issue by y9c** [brentp/pbr#4]
It would be great if the reference base of the site can be ouput into the pileup table, which would make it easy to call and filter mutation ratio of each site.

**Comment by brentp** [comment]
yes, I will add this it was an oversight. thanks for the reminder.

**Comment by y9c** [comment]
Hi @brentp, thank you for the update. But I think you might forget to read the fasta file in the `BasicProcessor`, and the output would be all null in the ref_base column (`.`).

**Comment by brentp** [comment]
It's still not working in latest release? I thought this was sufficient: https://github.com/brentp/pbr/blob/main/src/main.rs#L258

**Comment by y9c** [comment]
Yes. It is still not working. When I used the perbase_lib, 

I also add:

```rust
        let ref_buffer = Some(reference::Buffer::new(
            IndexedReader::from_file(&ref_fasta).expect("Reading Indexed FASTA"),
            ref_buffer_capacity,
        ));
```

```rust
        reader.set_reference(&self.ref_fasta).expect("Set ref");
```

**Comment by brentp** [comment]
ah. right. ok. I'll add this tomorrow as well. Or this would be much appreciated as a PR.
thanks either way.

**Comment by y9c** [comment]
Yes. I did try to add fasta support, but it made the tool much slower. I can wait for you update. Thanks.

**Comment by brentp** [comment]
Use the code that you posted above made it slower? Or you had additional code to extract the actual reference allele? 
Hmm, I was thinking it would handle it after adding that, but I see that's not the case.

**Comment by brentp** [comment]
I pushed a fix for this that adds caching to the Faidx so it doesn't hit the disk for every base.

**Comment by y9c** [comment]
Sorry for the late reply. It works now. Will it be better if the cache size can be adjusted?

**Comment by brentp** [comment]
It's a fair idea; I'd rather not as it adds confusion and docs, and for this library, it won't affect performance. With a cache size of 1000, we have 1000X fewer hits to the disk.

**Comment by y9c** [comment]
My situation may not be typical, as I sometimes try to extract data from numerous sites onto a given bed file. For example, I am interested in determining the base frequencies of 10,000 SNP sites. These sites are spread out and sparsely located, with a majority of them being approximately 1000 base pairs apart from one another.

**Comment by brentp** [comment]
I'll try to make the changes so your use-case is supported. Thanks for your feedback.
I wonder if you've seen/considered [hileup](https://github.com/brentp/hileup) which works well for sparse queries.
The python API might be lacking a way to get strand, but perhaps it's close to what you need.

**Comment by y9c** [comment]
Thank you for introducing hileup to me. Seems that this is what I am looking for. I will test it with my data.

**Comment by brentp** [comment]
ok. it looks like I encoded strand as upper/lower case in the python version so it is available.

**Comment by y9c** [comment]
Yes. Thank you for the information.
