### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by mkyriak** [brentp/pbr#6]
Hello,

Thank you for your effort and for this tool!
I was trying to install it as `sh build.sh` but I got this error `build.sh: line 5: cross: command not found`.

I am not sure if this is because of the cross compiler? I have already installed `perbase`. 

Am I missing something?

Thank you in advance!

**Comment by brentp** [comment]
hi, the build.sh is for me. But you can use it if you have cargo and cargo cross installed.
The simplest way is to get a linux binary from the releases [here](https://github.com/brentp/pbr/releases)
